version: '3.8'

services:
  dev:
    build:
      context: .
    ports:
      - "5001:3000" 
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  prod:
    build:
      context: .
    ports:
      - "5002:3000"
    environment:
      NODE_ENV: production
    command: npm run start
